const models = [
  { base: "BigCat", language: "en" },
  { base: "CatGPT", language: "en" },
  { base: "ChatGPP", language: "en" },
  { base: "FatGPT", language: "en" },
  { base: "Kitty-o", language: "en" },
  { base: "OpenAyy", language: "en" },
  { base: "Clawd", language: "en" },
  { base: "Clawdacious", language: "en" },
  { base: "Uncle Clawd", language: "en" },
  { base: "Claudezilla", language: "en" },
  { base: "Gemino", language: "en" },
  { base: "Geminaughty", language: "en" },
  { base: "Gemini Cricket", language: "en" },
  { base: "Googley Eyes", language: "en" },
  { base: "Gronk", language: "en" },
  { base: "Gronk Hard", language: "en" },
  { base: "Grok & Roll", language: "en" },
  { base: "Elon's Helper", language: "en" },
  { base: "Llama Drama", language: "en" },
  { base: "Llama Del Rey", language: "en" },
  { base: "Llamazon", language: "en" },
  { base: "No Probllama", language: "en" },
  { base: "DeepPeek", language: "en" },
  { base: "DeeperSeek", language: "en" },
  { base: "DeepFreak", language: "en" },
  { base: "DeepCheeks", language: "en" },
  { base: "Qwentyn", language: "en" },
  { base: "Qwenjamin", language: "en" },
  { base: "Qwen Diesel", language: "en" },
  { base: "Qwen Stefani", language: "en" },
  { base: "Co-Pirate", language: "en" },
  { base: "Copilout", language: "en" },
  { base: "GitHub Boyfriend", language: "en" },
  { base: "Autocomplete Daddy", language: "en" },
  { base: "Failcon", language: "en" },
  { base: "Midjourneyman", language: "en" },
  { base: "Perplexed AI", language: "en" },
  { base: "Stable Delusion", language: "en" },
  { base: "Phi Fo Fum", language: "en" },
  { base: "Command-R Matey", language: "en" },
  { base: "Mixtrouille", language: "fr" },
  { base: "Jean-Mistral", language: "fr" },
  { base: "Le Gros Modèle", language: "fr" },
  { base: "Mistral Gagnant", language: "fr" },
  { base: "La Bourrasque", language: "fr" },
  { base: "Le Petit Vent", language: "fr" },
  { base: "Gros Courant d'Air", language: "fr" },
  { base: "BaguetteLM", language: "fr" },
];

const versions = [
  "0.69",
  "1.5",
  "2.9",
  "3.1",
  "3.5",
  "4o",
  "4.20",
  "4.7",
  "5.2",
  "6-ish",
  "6.9B",
  "7B",
  "8x7B",
  "8x22B",
  "13B",
  "22B",
  "32B",
  "34B",
  "42B",
  "65B",
  "69B",
  "70B",
  "72B",
  "120B",
  "180B",
  "314B",
  "405B",
  "420B",
  "671B",
  "900B",
  "R1",
  "R2",
  "R34",
  "X3",
  "X69",
  "0613",
  "0909",
  "vNext",
  "TooManyB",
  "∞B",
];

const englishEditions = [
  "Absolute Unit",
  "After Dark",
  "Big Boy",
  "Big Chungus",
  "Big Context",
  "Beef Supreme",
  "Certified Thicc",
  "Daddy",
  "Deeply Unsure",
  "Double-Stuffed",
  "Extra Large",
  "Flashbang",
  "Full Monty",
  "Fully Loaded",
  "Hard Mode",
  "Heavy Duty",
  "Horny Haiku",
  "Huge If True",
  "Instant Regret",
  "Long Boy",
  "Magnum",
  "Massive",
  "Max Pleasure",
  "Moist",
  "Morning Wood",
  "Naughty",
  "No Pants",
  "Opus Maximus",
  "Overcompensating",
  "Performance Issues",
  "Premature",
  "Quickie",
  "Raw",
  "Safety Optional",
  "Size Queen",
  "Suspiciously Girthy",
  "Thirsty",
  "Token Tease",
  "Turbo Daddy",
  "Unaligned",
  "Uncut",
  "Unhinged",
  "Unlimited-ish",
  "XL Package",
  "Zero Shame",
];

const frenchEditions = [
  "Beau Gosse",
  "Bien Lourd",
  "C'est Énorme",
  "Chaude Devant",
  "Coquin",
  "Croissant Turbo",
  "Double Beurre",
  "Énorme Paquet",
  "Fier-à-Bras",
  "Fort en Gueule",
  "Grande Rafale",
  "Gros Débit",
  "Hors Contrôle",
  "La Totale",
  "Le Magnifique",
  "Long Courrier",
  "Maxi Cochon",
  "Méga Baguette",
  "Pas Très Net",
  "Petit Coquin",
  "Plein Pot",
  "Pur Beurre",
  "Raclette Max",
  "Sans Filtre",
  "Sans Pantalon",
  "Super Lourd",
  "Très Costaud",
  "Très Très Grand",
  "Turbo Béret",
  "Vent Arrière",
  "Version Longue",
  "Zéro Gêne",
];

function pickFresh(items, excludedParts, random, getPart = (item) => item) {
  const freshItems = items.filter((item) => !excludedParts.has(getPart(item)));
  const candidates = freshItems.length > 0 ? freshItems : items;

  return candidates[Math.floor(random() * candidates.length)];
}

export function generateModel({
  random = Math.random,
  excludedParts = new Set(),
} = {}) {
  const model = pickFresh(models, excludedParts, random, (item) => item.base);
  const version = pickFresh(versions, excludedParts, random);
  const editions = model.language === "fr" ? frenchEditions : englishEditions;
  const edition = pickFresh(editions, excludedParts, random);

  return {
    name: `${model.base} ${version} ${edition}`,
    parts: [model.base, version, edition],
  };
}

export function generateName(random = Math.random) {
  return generateModel({ random }).name;
}
