const models = [
  { base: "BigCat", language: "en" },
  { base: "CatGPT", language: "en" },
  { base: "ChatGPP", language: "en" },
  { base: "FatGPT", language: "en" },
  { base: "Kitty-o", language: "en" },
  { base: "OpenAyy", language: "en" },
  { base: "Clawd", language: "en" },
  { base: "Clawdacious", language: "en" },
  { base: "Uncle Clawd", language: "en" },
  { base: "Claudezilla", language: "en" },
  { base: "Gemino", language: "en" },
  { base: "Geminaughty", language: "en" },
  { base: "Gemini Cricket", language: "en" },
  { base: "Googley Eyes", language: "en" },
  { base: "Gronk", language: "en" },
  { base: "Gronk Hard", language: "en" },
  { base: "Grok & Roll", language: "en" },
  { base: "Elon's Helper", language: "en" },
  { base: "Llama Drama", language: "en" },
  { base: "Llama Del Rey", language: "en" },
  { base: "Llamazon", language: "en" },
  { base: "No Probllama", language: "en" },
  { base: "DeepPeek", language: "en" },
  { base: "DeeperSeek", language: "en" },
  { base: "DeepFreak", language: "en" },
  { base: "DeepCheeks", language: "en" },
  { base: "Qwentyn", language: "en" },
  { base: "Qwenjamin", language: "en" },
  { base: "Qwen Diesel", language: "en" },
  { base: "Qwen Stefani", language: "en" },
  { base: "Co-Pirate", language: "en" },
  { base: "Copilout", language: "en" },
  { base: "GitHub Boyfriend", language: "en" },
  { base: "Autocomplete Daddy", language: "en" },
  { base: "Failcon", language: "en" },
  { base: "Midjourneyman", language: "en" },
  { base: "Perplexed AI", language: "en" },
  { base: "Stable Delusion", language: "en" },
  { base: "Phi Fo Fum", language: "en" },
  { base: "Command-R Matey", language: "en" },
  { base: "Sama Drama", language: "en" },
  { base: "Altman Returns", language: "en" },
  { base: "ClosedAI", language: "en" },
  { base: "BoardroomGPT", language: "en" },
  { base: "DarioWare", language: "en" },
  { base: "Amodei & Sons", language: "en" },
  { base: "Ilya Saw It", language: "en" },
  { base: "Sutskever Prime", language: "en" },
  { base: "Safe Supermaybe", language: "en" },
  { base: "Yann LeCan't", language: "en" },
  { base: "LeCun Believe It", language: "en" },
  { base: "Karpathy Lite", language: "en" },
  { base: "Andrej 3000", language: "en" },
  { base: "Demis Enough", language: "en" },
  { base: "Hassabis Prime", language: "en" },
  { base: "Mira Mira", language: "en" },
  { base: "Murati Party", language: "en" },
  { base: "Jensen Signed", language: "en" },
  { base: "Leather Jacket LM", language: "en" },
  { base: "Zuck's Llama", language: "en" },
  { base: "Satya Later", language: "en" },
  { base: "Noam Shazoom", language: "en" },
  { base: "Fei-Fei Fly", language: "en" },
  { base: "Bengio Bingo", language: "en" },
  { base: "ReplyGuyLM", language: "en" },
  { base: "BlueCheckGPT", language: "en" },
  { base: "RatioNet", language: "en" },
  { base: "MainCharacterAI", language: "en" },
  { base: "VibeCoder", language: "en" },
  { base: "SlopEngine", language: "en" },
  { base: "Mixtrouille", language: "fr" },
  { base: "Jean-Mistral", language: "fr" },
  { base: "Le Gros Modèle", language: "fr" },
  { base: "Mistral Gagnant", language: "fr" },
  { base: "La Bourrasque", language: "fr" },
  { base: "Le Petit Vent", language: "fr" },
  { base: "Gros Courant d'Air", language: "fr" },
  { base: "Arthur Mensch", language: "fr" },
  { base: "Mensch Machine", language: "fr" },
  { base: "Le Gros Chat", language: "fr" },
  { base: "Start-up Nation LM", language: "fr" },
  { base: "BaguetteLM", language: "fr" },
];

const versions = [
  "0.69",
  "1.5",
  "2.0",
  "2.5",
  "2.9",
  "3.0",
  "3.1",
  "3.5",
  "3.7",
  "4",
  "4.1",
  "4.5",
  "4o",
  "4.20",
  "4.7",
  "5",
  "5.2",
  "6-ish",
  "6.9B",
  "7B",
  "8x7B",
  "8x22B",
  "13B",
  "22B",
  "32B",
  "34B",
  "42B",
  "65B",
  "69B",
  "70B",
  "72B",
  "120B",
  "180B",
  "314B",
  "405B",
  "420B",
  "671B",
  "900B",
  "o1",
  "o3",
  "o4-mini",
  "R1",
  "R2",
  "R34",
  "X3",
  "X69",
  "0613",
  "0909",
  "vNext",
  "TooManyB",
  "∞B",
];

const englishEditions = [
  "Absolute Unit",
  "AGI Internally",
  "Alignment Tax",
  "After Dark",
  "Benchmark Leak",
  "Big Boy",
  "Big Chungus",
  "Big Context",
  "Beef Supreme",
  "Blue Check",
  "Board Coup",
  "Community Noted",
  "Compute Poor",
  "Concerning",
  "Context Rot",
  "Country of Geniuses",
  "Definitely Open",
  "Deeply Unsure",
  "Delete This",
  "Evals Pending",
  "e/acc Turbo",
  "Feel the AGI",
  "Flashbang",
  "Founder Mode",
  "Full Monty",
  "GPU Poor",
  "Hard Mode",
  "Heavy Duty",
  "Huge If True",
  "Ilya Approved",
  "Ilya Saw It",
  "Instant Regret",
  "Looking Into It",
  "Long Boy",
  "Loss Curve",
  "Loving Grace",
  "Main Character",
  "Magnum",
  "MoE Problems",
  "Not Candid",
  "Opus Maximus",
  "Open Weights-ish",
  "Paperclip Max",
  "p(doom) Rising",
  "Performance Issues",
  "Please Clap",
  "Post Training",
  "Posting Through It",
  "Ratio Proof",
  "RLHF'd",
  "Scaling Pilled",
  "Safety Optional",
  "Safetywashed",
  "Source Needed",
  "Stochastic Parrot",
  "The Everything Model",
  "Thread Incoming",
  "Token Rich",
  "Unaligned",
  "Uncut",
  "Unhinged",
  "Unlimited-ish",
  "Verified Reply",
  "Vibe Checked",
  "Vibes Based",
  "What Ilya Saw",
  "Woke Weights",
  "World Model",
  "XL Context",
  "Zero Shame",
];

const frenchEditions = [
  "Beau Gosse",
  "Bien Lourd",
  "C'est Énorme",
  "Chaude Devant",
  "Coquin",
  "Croissant Turbo",
  "Double Beurre",
  "Énorme Paquet",
  "Fier-à-Bras",
  "Fort en Gueule",
  "Grande Rafale",
  "Gros Débit",
  "Hors Contrôle",
  "La Totale",
  "Le Chat Potté",
  "Le Magnifique",
  "Long Courrier",
  "Maxi Cochon",
  "Méga Baguette",
  "Mensch Approuvé",
  "Mistral Gagnant",
  "Pas Très Net",
  "Petit Coquin",
  "Plein Pot",
  "Pur Beurre",
  "Raclette Max",
  "Souveraineté Turbo",
  "Sans Filtre",
  "Sans Pantalon",
  "Super Lourd",
  "Très Costaud",
  "Très Très Grand",
  "Turbo Béret",
  "Vent Arrière",
  "Version Longue",
  "Zéro Gêne",
];

function pickFresh(items, excludedParts, random, getPart = (item) => item) {
  const freshItems = items.filter((item) => !excludedParts.has(getPart(item)));
  const candidates = freshItems.length > 0 ? freshItems : items;

  return candidates[Math.floor(random() * candidates.length)];
}

export function generateModel({
  random = Math.random,
  excludedParts = new Set(),
} = {}) {
  const model = pickFresh(models, excludedParts, random, (item) => item.base);
  const version = pickFresh(versions, excludedParts, random);
  const editions = model.language === "fr" ? frenchEditions : englishEditions;
  const edition = pickFresh(editions, excludedParts, random);

  return {
    name: `${model.base} ${version} ${edition}`,
    parts: [model.base, version, edition],
  };
}

export function generateName(random = Math.random) {
  return generateModel({ random }).name;
}
